# RBAC configuration for Ignite Kubernetes discovery
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite-account
  namespace: ignite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ignite-role
  namespace: ignite
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ignite-role-binding
  namespace: ignite
subjects:
  - kind: ServiceAccount
    name: ignite-account
    namespace: ignite
roleRef:
  kind: Role
  name: ignite-role
  apiGroup: rbac.authorization.k8s.io
